NO-ISSUE: Fix change `latest` tag to `main`

diff --git a/.github/workflows/osl_publish_images_snapshots.yml b/.github/workflows/osl_publish_images_snapshots.yml
--- a/.github/workflows/osl_publish_images_snapshots.yml
+++ b/.github/workflows/osl_publish_images_snapshots.yml
@@ -80,7 +80,7 @@ jobs:
         run: |
           for image in ${{ vars.PUBLISH_IMAGES_LIST }}; do
             echo "Pushing $image to Quay"
-            docker tag quay.io/kubesmarts/$image:${{ env.IMAGE_TAG }} quay.io/kubesmarts/$image:latest
+            docker tag quay.io/kubesmarts/$image:${{ env.IMAGE_TAG }} quay.io/kubesmarts/$image:main
             docker push quay.io/kubesmarts/$image:${{ env.IMAGE_TAG }} || { echo "Failed to push $image with tag $IMAGE_TAG to Quay"; exit 1; }
-            docker push quay.io/kubesmarts/$image:latest || { echo "Failed to push $image:latest"; exit 1; }
+            docker push quay.io/kubesmarts/$image:main || { echo "Failed to push $image:main"; exit 1; }
           done
